### ISSUE TITLE
Mass matrix in instationaryDiscretization not identity by default

### ISSUE THREAD

**Issue by fameyer** [pymor/pymor#103]
Hello!

In the documentation of the InstationaryDiscretization it is said that 

'mass
    The mass Operator M. If None the identity is assumed.' 

But as far as I see it, when mass=None upon instantiation in my code, mass stays None. Accordingly assertion errors occur later (when doing RB stuff).

Regards! Falk

**Comment by sdrave** [comment]
The intention is that the case 'no mass operator' should be interpreted as 'the mass matrix is the identity matrix'. I am not sure whether `mass` should be set to something like `IndentityOperator` by default, since this makes it harder to perform special treatment for this case. However, not providing a mass matrix should not lead to failing assertions, of course. Where does your code fail?

**Comment by fameyer** [comment]
I define an instationaryDiscretization with some Lincombperators like this:

`discretizaton = InstationaryDiscretization(operator = op, rhs=rhs, initial_data=u0, T=T, time_stepper = ImplicitEulerTimeStepper(n))`

So I do not provide a mass operator. When I now start a greedy search with this discretization I get following error:

`File "../pymor/src/pymor/algorithms/timestepping.py", line 125, in implicit_euler`
`assert isinstance(M,OperatorInterface)`
`AssertionError`

I debugged it with pdb and up to this point M = None is valid.

**Comment by sdrave** [comment]
Ah yes, I remember! Problem is that the implicit Euler code only works if you provide a mass matrix since it has to invert something like (I + A) in case the mass matrix is the identity. However, there is at the moment no generic way to obtain an appropriate operator representing the identity. `IdentityOperator` won't work since you will want to assemble a matrix for (I + A) in order to plug it into a linear solver.

Right know I can only ask you to specify an (identity) mass matrix if you want to use implicit Euler timestepping. I will leave this issue open until we have found a good approach for solving this. (I am open to suggestions ..)

**Comment by ftalbrecht** [comment]
We should let `assemble_lincomb` be smart to detect the identity operator...

**Comment by sdrave** [comment]
So, this should work now:

- a16a482f54b1e3317b54a177cfc3b3bb61a5acac extends `implicit_euler` to use `IdentityOperator` as mass matrix if none is supplied.
- 32e43034b085758936d198332472b84c5b283a56, ee35db4556e6e78325b84edcdcb99f87aab4689a implement support for assembling linear combinations of NumpyMatrixOperators and IdentityOperators, so (I + A) can be inverted efficiently (without falling back to generic solvers).

**Comment by sdrave** [comment]
Still, the question remains if the mass matrix in InstationaryDiscretization should never be `None`.
Note:

> If `mass` is `None`, `reduce_generic_rb` will also set it to `None` for the reduced discretization. 

Thus, we will, usually, get mathematically  wrong results, when `mass` is `None`, but `reduced_basis` is not orthonormal w.r.t. the Euclidean inner product.

On the other hand, `reduce_generic_rb` currently does not know if `reduced_basis` is orthonormal or not. So setting `mass` to `IdentityOperator` will give an unneeded `NumpyMatrixOperator` holding the identity matrix, which would also have to be inverted for an explicit timestepping scheme. This situation has to be avoidable.

Possible solutions:
- Allow `mass` to be `None` (current situation). Downside: user has to know that `reduced_basis` has to be orthonormal w.r.t. Euclidean inner product. Otherwise, false results will be obtained.
- Let `mass` be `IdentityOperator` if none is provided. Give `reduce_generic_rb` an additional argument which informs it about the orthonormality of `reduced_basis`. If it is, replace `IdentityOperators` by `IdentityOperators`. Downside: does not work for `IdentityOperators` which are part of `LincombOperator`, etc. However, this would not be a very big performance issue online, probably.
- Let `mass` be `IdentityOperator` if none is provided. Numerically detect in `projected` of `IdentityOperator` that the projected matrix is the identity. Downsides: have to pay `reduced_basis.gramian()` for each `IdentityOperator` during projection in the offline phase. Numerical issues?

My feeling is that we should give the user the responsibility and keep things as they are. The seconds option seems too clumsy for only handling a very specific case (most `InstationaryDiscretizations` will have a mass matrix). The third options is more interesting, but I would fear that the magic might fire back on us.

Other opinions?

**Comment by sdrave** [comment]
Regarding @fameyer's first comment, we should probably clarify the documentation ...

**Comment by ftalbrecht** [comment]
I tend to favor the first option atm...

**Comment by sdrave** [comment]
I just tried to implement the second option but did not come to satisfying results. Adding an extra option to `reduce_generic_rb` just to handle the mass matrix feels wrong, in particular as we cannot pass it on to nested `IdentityOperators`. My general impression is still that we should remove `projected` from `OperatorInterface` and switch to a rule based approach to reduction algorithms (as done in symbolic algebra systems). Of course this will not happen before 0.4, so I agree to leave things as they are for now.

**Comment by sdrave** [comment]
See #208.
