### ISSUE TITLE
NotImplementedError for sparse NumpyMatrixOperator 

### ISSUE THREAD

**Issue by meretp** [pymor/pymor#1096]
I wanted to test the samdp algorithm with some of the Oberwolfach benchmarks. For this I created a LTIModel from the matrices contributed on the MORWiki. Using the following code

`fom = LTIModel.from_matrices(A,B,C)`
`poles, res, rev, lev = samdp(fom.A, None, fom.B.as_range_array(), fom.C.as_source_array(), 20)`

I got a NotImplementedError because the matrices B and C are sparse.

What is the reason for the as_range_array() and the as_source_array() method for NumpyMatrixOperator to check if the given operator is sparse and throw a NotImplementedError if it is?

**Comment by sdrave** [comment]
> What is the reason for the as_range_array() and the as_source_array() method for NumpyMatrixOperator to check if the given operator is sparse and throw a NotImplementedError if it is?

`NumpyVectorArrays` store their data as a dense NumPy array. As such, the code in `NumpyMatrixOperator.as_range_array/as_source_array` would not work for a sparse matrix. To make it work, a conversion from sparse to dense would be necessary. In many cases, this is not feasible/desired, and it is better to throw an error.

However, if there are relevant use cases, I could imagine to support this. (We can simply call `super().as_range_array/as_source_array.) While we are at it, I could imagine to guard `Operator.as_range_array/as_sourcearray` with a configurable threshold for the small dimension, above which the calls fail instead of blowing up the computer. @pmli, @lbalicki, what do you think?

**Comment by lbalicki** [comment]
I like the idea of adding a threshold for the small dimension. In many benchmarks the `B` and `C` matrices of an `LTIModel` are stored in sparse format although they only have very few rows/columns. Adding the threshold would prevent that the user has to call e.g. `B.toarray()` when initializing the `LTIModel` in order to use algorithms like `lradi` and  `samdp`.

**Comment by pmli** [comment]
I agree it would be good to have a finite threshold to not blow up the user's computer by accident, but I'm not sure what would be a good default (maybe something related to [`sparse_min_size`](https://github.com/pymor/pymor/blob/4fc3893a3746da584aa006db24f9ec210f366cba/src/pymor/models/iosys.py#L24)?) or if that's the nicest approach.

I guess another option would be allowing SciPy sparse matrices in `NumpyVectorArray` (maybe with a more appropriate name...). @sdrave, do you think this would be feasible?

Yet another option, and maybe the easiest, would be to raise something like `ValueError('matrix is sparse. Create a NumpyMatrixOperator with a dense array.')` instead of `NotImplementedError`, but I'm not sure how nice it is.

**Comment by sdrave** [comment]
> I agree it would be good to have a finite threshold to not blow up the user's computer by accident, but I'm not sure what would be a good default (maybe something related to [`sparse_min_size`](https://github.com/pymor/pymor/blob/4fc3893a3746da584aa006db24f9ec210f366cba/src/pymor/models/iosys.py#L24)?) or if that's the nicest approach.

Ok, then let's do it like that. I would say we simply attach defaults to `Operator.as_range_array` and `Operator.as_source_array`. I would got with 100 as a default (as the second dimension could be very large). Obviously, there will be no universally good default ..

> 
> I guess another option would be allowing SciPy sparse matrices in `NumpyVectorArray` (maybe with a more appropriate name...). @sdrave, do you think this would be feasible?

I don't think this is a good idea. This would probably be a lot of work and many interface methods would have super bad performance. Also, I don't really see the use case.

> Yet another option, and maybe the easiest, would be to raise something like `ValueError('matrix is sparse. Create a NumpyMatrixOperator with a dense array.')` instead of `NotImplementedError`, but I'm not sure how nice it is.

Would agree to that as well. But if many `B` and `C` matrices come as sparse matrices, I think it makes sense to make things more convenient.

**Comment by pmli** [comment]
> Ok, then let's do it like that. I would say we simply attach defaults to `Operator.as_range_array` and `Operator.as_source_array`. I would got with 100 as a default (as the second dimension could be very large). Obviously, there will be no universally good default ..

Ok, sounds good. I was thinking about somehow limiting both dimensions, but limiting the smaller one should be good enough.

> I don't think this is a good idea. This would probably be a lot of work and many interface methods would have super bad performance. Also, I don't really see the use case.

True, it would affect many places.

> Would agree to that as well. But if many `B` and `C` matrices come as sparse matrices, I think it makes sense to make things more convenient.

I'm not sure how many Oberwolfach benchmarks have them, but it would be convenient not to think about it when building models.
