### ISSUE TITLE
Caching in LTIModel.gramian

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#1115]
Calling `gramian` for a non-parametric `LTIModel`, once with `mu=None` and once with `mu=Mu({})`, will compute the same Gramian twice. I noticed this issue when calling `h2_norm()` and `gramian('c_lrcf')` separately (`h2_norm` calls `gramian` with `mu=Mu({})`).

Here is an example code:

```python
import numpy as np
import scipy.sparse as sps

from pymor.models.iosys import LTIModel
from pymor.parameters.base import Mu

n = 2000
d0 = n * [-2]
d1 = (n - 1) * [1]
A = sps.diags([d0, d1, d1], [0, -1, 1], format='csc')
B = np.ones((n, 1))
C = np.ones((1, n))

fom = LTIModel.from_matrices(A, B, C)

print(fom.gramian('c_lrcf'))
print(fom.gramian('c_lrcf', mu=Mu({})))
```

Should `gramian` be implemented as `Model.solve` (use a private `_gramian` for the cached call)? Also for other `@cached` methods in `pymor.models.iosys` (`freq_resp`, `poles`, `_hsv_U_V`, `h2_norm`, `hinf_norm`)?

**Comment by sdrave** [comment]
Having a cached `_gramian` so that you can preprocess `mu` is probably the only option. (Note that you will still get cache misses when you add some parameter value the `Model` actually does not depend on. However, this is probably much more unlikely to happen.)

Otherwise: Maybe `mu=None` is actually a bad choice and we should use `mu=Mu()` everywhere. Would make it a little bit more tedious to write signatures, but the advantage would be that the `mu` parameter always has the same type.

**Comment by pmli** [comment]
> Otherwise: Maybe `mu=None` is actually a bad choice and we should use `mu=Mu()` everywhere. Would make it a little bit more tedious to write signatures, but the advantage would be that the `mu` parameter always has the same type.

Then there would be the issue with parametric models, right? For example, when using `mu=1` vs. `mu=Mu({'p': 1})`.

**Comment by sdrave** [comment]
Yes this can only be circumvented via `cached_method_call` in a wrapper method calling `self.parameters.parse`. I guess another option would be to allow something like

```python
@cached(mu=lambda self, mu: self.parameters.parse(mu))
def cached_method(self, args, mu=None)
    pass
```
