### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/pymor#126]
We decided to switch to a Copyright statement in the spirit of

```
Copyright (c) 2015 by the pyMOR developers. All rights reserved.
...
```

* We have to check wether this will result in any legal issues for us.
* We have to check wether we can use this from now on or wether we have to include the old statement below for existing files (current opinion was to keep the old statement in existing files).

**Comment by sdrave** [comment]
Just to sum up a discussion I just had with @gramian. A possible solution might be:

- Header:

```
# This file is part of the pyMOR project (http://www.pymor.org).
# Copyright (c) 2015 by the pyMOR developers and contributors. All rights reserved.
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
#
# Contributors: Foo Bar <foo@bar.org>
```

- `DEVELOPERS.TXT` defines the list of pyMOR (core) developers who own the rights at the project as a whole.
- Every contributor holds the copyright to her own contributions.
- This will make relicensing impossible.
- Only non-trivial contributions (not fixing a few typos in the documentation, fixing trivial bug) allow you to be mentioned in the contributors list. Thus, the list of contributors should be manually maintained.
- Contributors are allowed to add more extensive attribution notices (citing papers, etc.) to their contributions, as long as BSD 2-Clause is maintained. pyMOR core developers share the copyright. (*Is this really needed, or can the contributor, e.g., for a single algorithm hold exclusive copyright?*)
- Release notes (which should become part of the documentation) should mention all major contributions during the release cycle.

**Comment by renemilk** [comment]
Sounds good to me :+1:

**Comment by ftalbrecht** [comment]
The one thing I do not like about this is the need to manually maintain the list of contributors. This sounds like a lot of fun just before the release: someone needs to go through all the files in pyMOR, needs to take a look at all contributions and needs to decide for each contribution whether it is worth to be mentioned or not...

What is the problem with letting git automatically create the list of authors per file, do we fear that we will have too many authors per file?

**Comment by sdrave** [comment]
@ftalbrecht, its not as if we would have hundreds of contributors. I really do not see how we would detect trivial changes in an automatic way. Do you really want to give someone who fixed some documentation typos in 20 files copyright for all these files? Why do we not make it the contributors' responsibility to add their names (with possible comments) to all relevant files and the upcoming release notes when they contribute something?

**Comment by sdrave** [comment]
Ok, so I did some further research:

Regarding the copyright one should note that under current US law, a copyright notice is actually [optional](http://www.copyright.gov/circs/circ03.pdf) to retain copyright (although it is recommended to strengthen your position in case of a lawsuit). Moreover, in several countries including Germany, copyright cannot be (fully) transfered to another entity. The BSD license requires us to have a copyright notice (which must be reproduced together with the license text).

A [contributor license agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement) hands over copyright or gives a license to the project owner in order to
* allow the project to publish the code under the project's license.
* allow relicensing.
* give the project owner the ability to sue someone violating the project's license.
* Moreover, it covers patents possibly associated with the contribution

These questions become obviously more important when the contributed code is owned by a company and/or the project owner is a company. The opinions on what a legally sufficient way of accepting a CLA is vary widely. E.g. the FSF seems to have changed their policy from requiring a dead-tree letter to accepting GPG signed documents. There are also [some]( https://cla-assistant.io/) [bots](http://clabot.github.io/) which aim at automating the CLA acceptance process when a new pull request is opened on github.

[Here](http://oss-watch.ac.uk/resources/cla) [are](http://www.pro-linux.de/news/1/20689/debatte-ueber-contributor-license-agreements.html) [some](http://ebb.org/bkuhn/blog/2014/06/09/do-not-need-cla.html) articles discussing CLAs of which I found the last one to be very convincing.
My POV is the following:

1. BSD is already one of the most liberal licenses out there, so there is no need to change the license to something less restrictive (e.g. like changing DUNE from GPL2 to LGPL or even GPL3 to make it compatible with the apache license). Derived/future work can always be published under a more restrictive license, and there is no pulling back for what has already been published under BSD (with or without CLA).
2. I do not realistically see myself suing someone for violating pyMOR's BSD license. Reverse engineering a commercial code to check if there are some pyMOR tidbits inside without naming us?
3. Regarding someone suing us. First of all, I do not really see this coming. And even when, since we are not doing this for profit it will probably always be easy to come to an agreement by removing the relevant code. The last article names as a better alternative to CLAs to use a 'Developer Certificate of Origin' to be on the safe side. Still, I do not feel that it is really necessary for the contributor to formally sign anything.

---

Similar to what I have written earlier, I propose to take the following actions:

* Each file has the following header: 
  
     >  # This file is part of the pyMOR project (http://www.pymor.org).
     >  # Copyright YEARS pyMOR developers and contributors. All rights reserved.
     >  # License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
* The same copyright notice is used in LICENSE.
* CONTRIBUTING.MD (#67) will contain a section which states that by using the obvious ways (pull requests, patch to the mailing list) the contributor gives us the right to license the code under pyMOR's (current) license.
* AUTHORS.MD lists the current pyMOR main developers (with push access) and all contributors (with more than a trivial contribution) with their contributions (text description). I propose to have a new contributors list for each release (of course, keeping the older lists).
* CONTRIBUTING.MD will contain a passage on how to become a main developer.
* As soon as we have relevant publications, we will ask users to cite our publications. The list can also contain publications by non-main developers when they cover a major contribution to pyMOR.
* Contributors can decorate the contributed code to their liking with names of authors, papers, funding institutions etc.
* We DO NOT automatically or manually maintain a list of contributors per source file as it is simply not feasible: automatic generation will easily add lots of names for trivial contributions; doing it manually is a lot of work, and with each refactoring you do not know which names are where appropriate. Apart from that, such a list is not very useful as you have no clue who has done what. And there is always git history.
* When a new contributor opens a pull request we will as part of the pull request discussion ask if the legal parts of CONTRIBUTING.MD have been read and understood. - We could use one of mentioned bots for this, but for now I believe this is overkill.

**Comment by ftalbrecht** [comment]
Sounds good to me! Thanks for crawling the internet!

**Comment by renemilk** [comment]
Entirely agreed.

**Comment by sdrave** [comment]
Just for future reference: FSF [recommends](https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html) to have the same date range for all files of the project.

**Comment by gramian** [comment]
This could also be of interest: https://www.bitkom.org//Publikationen/2016/Leitfaden/Open-Source-Software-20/Bitkom-Leitfaden-Open-Source-Software-20.pdf

**Comment by sdrave** [comment]
The changes are now in master: 3285677a73b0a2c6442b16590139bd5ad80c4d02.
