### ISSUE TITLE
Operator._radd_sub incompletely implemented

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#1285]
Right now, the method simply returns `None` in case `other` is an `Operator`. This obviously does not make any sense. The issue dates back to 1f7017448ba6a7f251c6b487d7d987b74e54c79a. @TiKeil, can you take a look?

BTW, mypy found the bug ...

**Comment by TiKeil** [comment]
Thanks for reporting that mypy found this. 

I would say this is not a really a bug but rather bad coding. It will essentially never happen that `other` is an `Operator` in this function unless someone calls `_radd_sub` explicitly which is not intended, I suppose. For all other cases, the code ends up in `_add_sub` directly. To make mypy happy, we should probably just call `_add_sub` instead of doing nothing.

**Comment by sdrave** [comment]
Ah sorry, didn't think this through. Then it's probably fine to just assert that `other` is not an Operator (just to make clear that this cannot happen) and then unconditionally return `NotImplemented`.
