### ISSUE TITLE
Blockdiag and stacking of operators and vector arrays

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#132]
This issue comes up when subtracting two LTI systems. If (A1, B1, C1, D1, E1) and (A2, B2, C2, D2, E2) are two LTI systems, then their subtraction is (blockdiag(A1, A2), vstack(B1, B2), hstack(C1, -C2), D1 - D2, blockdiag(E1, E2)).

Would you consider adding blockdiag, vstack, and hstack constructions/methods for operators and vector arrays (right now I have A and E as operators, and B and C as vector arrays)?

**Comment by ftalbrecht** [comment]
@sdrave: do you think we could/should realize this using the proposed block operators and vector arrays?
@pmli: in the context of the LRBMS I required blocked operators and vector arrays, that might be related to what you desire. They are not part of pyMOR (yet), as we were not yet finished considering the matter.

**Comment by sdrave** [comment]
`BlockVectorArray` is already in official master. Using it basically gives you the vstack operation. If I am not mistaken, hstack in your case really is vstack, as the whole array is transposed, so to say.
A block diagonal operator working on `BlockVectorArrays` has not been implemented yes, AFAIK, @ftalbrecht? Should be quite easy to implement, and I am happy to add it to pyMOR.

You might get into trouble, if you want to put these arrays and operators into external solvers. For now, I would propose to check in these cases the types of the blocks and assemble everything as needed when calling the solver.

**Comment by pmli** [comment]
Great!

Yes, hstack for C is actually vstack, if C stays a `NumpyVectorArray`.

I would expect for a block diagonal operator to behave like a `NumpyMatrixOperator`, i.e. to have all (four) apply methods and `assemble_lincomb` with another block diagonal operator or identity operator.

**Comment by ftalbrecht** [comment]
My initial implementation of the `BlockOperator` did have a specialization for only diagonal blocks. You were able to extract all operators associated with subblocks (to do whatever you like). I also provided an initial `assemble_lincomb` variant that just called the method on all contained operators and formed a new `BlockOperator`. `apply_inverse` was also implemented for numpy based operators by assembling all in one big (sparse) matrix and inverting that one.

All of this is [still there in my fork](https://github.com/ftalbrecht/pymor/blob/block-operator/src/pymor/playground/operators/block.py), but not up to date any more and would need some polish. Perhaps we can use this issue here to discuss the above implementation and to bring it back into shape. As far as I remember we at least wanted to split this into several classes, .e.g., a `BlockOperatorInterface`, `BlockDiagonalOperator` and `NumpyBasedBlockOperator`, or something like that...

**Comment by pmli** [comment]
I would prefer to have `apply_inverse` a bit more efficient. Instead of solving with a big matrix, I would propose solving two smaller systems. Also, it would be nice if the two blocks could be of different types, e.g. one sparse and one dense (this makes sense when comparing original and reduced system).

**Comment by ftalbrecht** [comment]
Solving two smaller systems could be implemented in the designated `BlockDiagonalOperator`. Other implementations of `apply_inverse` could be triggered by appropriate options (once #122 is resolved). For matrix-based non-diagonal operators, one option should be whether the resulting matrix is left sparse or converted to dense (e.g., for a reduced system).

**Comment by sdrave** [comment]
I also believe we should have a dedicated `BlockDiagonalOperator`. Calling `apply_inverse` on each subblock is a nice generic implementation ..

**Comment by sdrave** [comment]
@ftalbrecht, I think this is also an interesting case w.r.t. #183. On the one hand, think of a `BlockDiagonalOperator` where blocks have different operator backends. It is then very easy to specify options for both backends in the `solver_options` of the `BlockDiagonalOperator`. (The alternative would be to have somehow a list of options for each sub-operator.)

The other situation would be that you have blocks of the same type but you want different options for each operator. With #183, there is no way to specify new options for each sub-block, so you would have to update the sub-operators accordingly.

**Comment by pmli** [comment]
@sdrave @ftalbrecht I had to switch B and C to being operators, not vector arrays (I found an application with a large number of outputs and where C is sparse-plus-low-rank). Therefore, I'm now interested in `BlockOperator` created by vertical or horizontal stacking of operators. I'm also interested in more abstract `BlockOperator` and `BlockDiagonalOperator`, where blocks can be operators defined by mappings (e.g. `NumpyGenericOperator`).
Can I work on the block-operator branch? Could you propose an inheritance structure for `BlockOperator` and `BlockDiagonalOperator`?

**Comment by ftalbrecht** [comment]
@pmli: we have had a look at the old branch and a small design discussion about block operators. It is most welcome if you want to work on those! I would suggest not to use the old branch but rather to start a fresh branch from current master and add the operators to the playground (i.e., `pymor/playground/operators/block.py`), as the old branch is rather outdated. (Note that I will often call the individual operators corresponding to a block _local operator_ below.) We think there should be

* a `BlockOperator`, which is initialized by a two-dimensional numpy array (data type `object`), where each entry may be either `None` or an operator, thus resulting in a possibly sparse structure of operators.
  * `__init__` has to perform the necessary checks, perhaps you can have a look at the old branch for inspiration. In particular we require at least one operator per row and column of the numpy array and all operators per row and column must have identical source and range.
  * the source and range of the resulting `BlockOperator` should be a vector space consisting of the local vector spaces per row and column, see also the old branch. Thus `BlockVectorArray`s will be acceptable source and range types.
  * initially we decided to keep the numpy array of operators as a plain attribute `self.blocks`. @sdrave: in `BlockVectorArray` these are stored as `self._blocks` and (copy) access is granted via `v.block(i)`. We could also do the same here to be closer to `BlockVectorArray`, but then we would have to provide an attribute giving us the shape of `self._blocks`, so this is perhaps over-engineered. In addition, operators are immutable so there is no need to guard against direct access.
  * There should be (conveniece) class methods `hstack` and `vstack` which accept a (one-dimensional) array, list, tuple or iterable of operators and construct the appropriate two-dimensional numpy array of shape `1xlen(operators)` (hstack) or `len(operators)x1` (vstack) and returns a `BlockOperator`.
  * You can generically implement `apply` by applying the local operators to the respective block of the source and adding the results to the respective block of the range.
  * You can implement some methods required by operator interface (and check for linearity of the local operators in `__init__`), but there is no point in implementing `apply_inverse`, `apply_inverse_adjoint`, `jacobian` and `projected` at the moment, so perhaps you should raise an appropriate exception there.


* a `BlockDiagonalOperator`, derived from `BlockOperator`.
  * The main addition of this operator is to provide `apply_inverse` by calling the appropriate method on each local operator.
  * `__init__` should accept a one-dimensional structure of operators and create the appropriate two-dimensional array.
  * @sdrave: do we want to have an additional attribute `self.diagonal`, which will be a one-dimensional numpy array?
  * @sdrave: any idea on how to handle the `solver_options` of this operator? For the moment perhaps it is best not to have any options in this operator, since each local operator will know what to do and the user  can change those prior to creating the `BlockDiagonalOperator`

We also began to discuss possible implementations of `projected` and implications for the generation of a reduced basis, but we are not yet finished/happy there. Do you require those? Otherwise I would leave those unimplemented until we sort things out...

**Comment by pmli** [comment]
Thank you very much for the specification!

I actually never used `projected`, but `apply2`. It's kind of important to have access to the reduced A matrix (for the eigenvalue decomposition used in IRKA).

**Comment by sdrave** [comment]
> initially we decided to keep the numpy array of operators as a plain attribute self.blocks. @sdrave: in BlockVectorArray these are stored as self._blocks and (copy) access is granted via v.block(i). 
We could also do the same here to be closer to BlockVectorArray, but then we would have to provide an attribute giving us the shape of self._blocks, so this is perhaps over-engineered. In addition, operators are immutable so there is no need to guard against direct access.

I would say we should adapt `BlockVectorArray` accordingly. It would probably be a good idea to make the array immutable by calling `the_array.setflags(write=False)` after creation. For `BlockVectorArray` another option would be using a tuple, but a numpy array would be more coherent.

> @sdrave: do we want to have an additional attribute self.diagonal, which will be a one-dimensional numpy array?

Don't think so. If `op.blocks` is a numpy array, you can simply get the diagonal as `op.blocks.diagonal()`.

> @sdrave: any idea on how to handle the solver_options of this operator? For the moment perhaps it is best not to have any options in this operator, since each local operator will know what to do and the user can change those prior to creating the BlockDiagonalOperator

Yes, this is what we had discussed. `FixedParameterOperator` does not allow setting `solver_options` for the same reasons: allowing it would make the implementation more complicated, there is no real use, and many operators in pyMOR do not allow setting `solver_options`, so trying to change them (via `op.with_(solver_options=...)`) would lead to errors anyhow.

**Comment by sdrave** [comment]
> I actually never used projected, but apply2. It's kind of important to have access to the reduced A matrix (for the eigenvalue decomposition used in IRKA).

If you derive from `OperatorBase`, a default implementation for `apply2` (which you may or may not want to use) comes for free.

**Comment by sdrave** [comment]
@pmli, I would like to feature freeze master for the 0.4 release in a few weeks. Do you have some code which is more or less ready for inclusion in official pyMOR or should we postpone this issue for the next release?

**Comment by pmli** [comment]
Next release...

**Comment by sdrave** [comment]
Implemented in #215.
