### ISSUE TITLE
Set defaults on all ranks

### ISSUE THREAD

**Issue by josefinez** [pymor/pymor#1329]
As mentioned in the dev meeting, we are using a script where it is necessary (for now) to set the defaults on all ranks, even though it's an MPI distributed model.
When #1317 is approved, it's not a problem anymore. It could become one again, as long as it is possible to execute any default dependent code per rank in MPI wrapped distributed models.
But if no one else struggles with using the defaults on ranks>0, it might not be worth trying to solve it right now.

Anyway, I'm currently thinking of:
- checking if the script is executed with MPI in set_defaults and then broadcasting a method to update the defaults on all ranks
and
- checking if the number of `default_changes()` is equal on all ranks before starting the event loop in tools.mpi.

But I'm not sure how it is supposed to behave with worker pools and if there are other edge cases that have to be considered.

Maybe someone has an opinion on it?

**Comment by sdrave** [comment]
I think that in general `set_defaults` should synchronize defaults across all MPI ranks / `WorkerPool` workers, and the plan of action might be as follows:

- ATM you generally can't know on rank 0 whether or not the event loops are running on the other ranks or not. It can make sense not to use the `auto_launch` mechanism but only run the event loop at a later point in time. To have have this information on rank 0, we should have a `launch_event_loop` method in `tools.mpi` which the user has to simultaneously execute on all ranks. On rank 0, the loop actually won't be fired up, but some global state be set such that we know for the future that the even_loop is running. Further, the current defaults on rank 0 are communicated an set on all other ranks.

- When `set_defaults` is called on rank 0 and the event loop is running, the changes are automatically communicated to all ranks.

- When a new `WorkerPool` is initialized, the current defaults must be communicated to all workers. Since `MPIPool` relies on the event loop mechanism, this is only really necessary for the `IPythonPool`. When jobs are scheduled via the worker pool, the pool has to check whether `defaults.defaults_changes()` has increased. If so, the new defaults have to be communicated to all workers before executing the jobs.

@TiKeil, am I missing anything? In particular, are there any applications, where one would want to have different defaults for each worker / mpi rank. Are these important enough to be supported by pyMOR?
