### ISSUE TITLE
Provide better support for logical operations / specification of intervals in Expressions

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#1438]
Possibilities include adding support for `&`, `|`, `~` or having an `InInterval(x[0], -1, 1)` expression.

**Comment by sdrave** [comment]
With #1576, it should also be relatively easy to properly handle two-sided comparisons like `a < x[0] < b` or boolean operators.

**Comment by bergdola** [comment]
Hello,

I am interested in contributing to pyMOR, especially to this issue. Thinking about this feature request, some questions came up to me: 

- Since the issue is asking for better support for logical operators, do you mean logical operators when referring to &, | and ~ in the first comment or the bitwise and/or/negation as what &, | and ~ refer to in python? 
- As far as I understand, handling two sided-comparisons like a < x[0] < b ( which is equivalent to a < x[0] AND x[0] < b) are not that easy to solve with the current implementation approach, since python does not offer a magic method for boolean operations like AND. Could it be a suitable way to implement a function IsInInterval, checking the two sided-comparison, to be used in the Expression?

Looking forward to hearing from you, 
Anja

**Comment by bergdola** [comment]
Hello,
further thinking about the mentioned function InIntervall, two ideas of implementing came up to me:

1. implement "InIntervall" as a predefined function that can be called in an expression string similar to sin or cos.

2. implement a new class, e.g. ExpressionFunctionWithLimitedSupport, or add a new parameter "support" to ExpressionFunction to restrict the evaluation of the expression string to the intervall given by "support". Outside the intervall the function is zero. One could use LinComb if such multiple definitions are to be combined.

@sdrave Which way would be more suitable for the pyMOR project?

Looking forward to hearing from you,
Anja

**Comment by sdrave** [comment]
Hi @bergdola, it's great to hear that you are interested in contributing to pyMOR. Sorry for the late reply! 

I think adding a notion of support to functions would be overkill. Having an `InInterval` builtin is fine. Currently, one would have to write `(x[0] > -1) * (x[0] < 1)` to define an indicator function for the interval (-1, 1). Writing `InInterval(x[0], -1, 1)` would be much clearer.

Regarding two-sided comparisons: You are right that the main issue is that Python does not have an `__and__` method. And, although Python does have syntax for two-sided comparisons, there is also no magic method for handling these comparisons. However, the two-sided comparison is still visible in the AST, so one could at least extend `parse_expression` to transform the AST similarly to what is done for literals and replace a two-sided comparison by an `InInterval` expression.

If you want to tackle this issue, let me know if you need any help.

**Comment by bergdola** [comment]
Thank you for the kind reply, @sdrave .

Your explanation of the transformation of the AST helped me a lot, I now got a better idea of what is needed and I would like to work on the extension for parse_expression to support two-sided comparisons.

Would it be okay to focus on that in this issue without adding support for &, | and ~ as they are bitwise operators?

**Comment by sdrave** [comment]
> Would it be okay to focus on that in this issue without adding support for &, | and ~ as they are bitwise operators?

Sure.

**Comment by bergdola** [comment]
Hello @sdrave ,  

as discussed, I implemented a tree transformation for chained comparisons and created a draft pull request.

A chained comparison like “1<x[0]<2” is transformed to two joined comparisons “(1<x[0]) * (x[0]<2)”, as in the example. Is this mapping suitable or would you prefer another mapping, e.g. with numpy.logical_and? 

Should chained comparisons within array subscripts be implemented as well?

**Comment by sdrave** [comment]
See my comments to to #1898.
