### ISSUE TITLE
unresolved Flake8 issues

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1551]
To summarize #1547 (please correct me if I missed anything @artpelling):

There's a bunch (around 32) of docstrings violating D205 that should be dealt with. Options:
1. ignore D205 globally
1. mark only offending to be ignored
1. reword offending docstrings

I don't like option 1. I like the third the best, but that could be hard in places. I'm fine with option 2. as a compromise. Once we agree on the resolution this becomes a 'good first issue'.

There's a single digit amount each of D202, D402, D403, W505 too, but those should be straightforward to fix with no additional discussion necessary IMO.

If we include `docs` in the `flake8` run (ie with `pre-commit run -a`), there's a few F821 to fix too.

**Comment by sdrave** [comment]
I'd go with 3.

**Comment by artpelling** [comment]
I have just encountered the error `RST219 Inline substitution_reference start-string without end-string.` When adding
```
:math:`a,b,c,d\in\mathbb{C}`
```
to a class docstring. As far as I can tell, this is correct syntax. I had to temporarily disable the pre-commit hook in order to fix this. Our CI Linter did not seem to bother about it.
