### ISSUE TITLE
test demo skips too much

### ISSUE THREAD

**Issue by renefritze** [pymor/pymor#1691]
https://github.com/pymor/pymor/pull/1690#issuecomment-1187623678

**Comment by HenKlei** [comment]
> I don't really understand my linked comment there. @HenKlei any idea what I wanted to actually here?

I should, right? If I remember correctly, there was a problem with running the second example of the demo where fenics is not required. I think the problem arose when running the demo on a system without fenics but with torch where the whole demo was not executed because of missing fenics. But if I understand the fix in #1690 correctly, now that problem should not occur anymore, right? Whenever torch is available, at least one version of the demo is executed, or not?

**Comment by renefritze** [comment]
Yeah, that's why I'm confused too. I guess we can close this.
