### ISSUE TITLE
Operator to NumpyMatrixOperator or NumPy array

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#234]
There are a few methods I need that can currently only work with dense matrices, e.g. H_inf-norm computation. Some day, there might be standard large-scale versions of these methods that can work with operators, but I would like to use what I can now.

@sdrave What do you think about adding something like a `tonumpy` method to `OperatorInterface`? Or at least a version of `_matrix` from `NumpyMatrixOperator` to `BlockOperator` of `NumpyMatrixOperator`s and other constructions from `NumpyMatrixOperator`s?

**Comment by sdrave** [comment]
I am very open to adding provisions to make directly dealing with matrix data more easy. pyMOR's current design is quite puristic and to make it usable for a wider audience, direct data access should be "officially" supported. Some thoughts:

1. I am somewhat hesitant to add data access methods directly to the `OperatorInterface`. pyMOR's current main selling point is that all its algorithms work without direct data access. I feel that if we add/encourage algorithms which need this access by adding respective methods to the interface, we undermine this design principle. It might also become hard to distinguish between generic algorithms and those which require data access.

2. Adding something like a `OperatorWithDataAccessInterface` subclass or an `DataAccess` mixin will  not work. If `BlockOperator` allows data access, depends on the types of the sub-blocks and not on the `BlockOperator` itself.

3. Regarding `NumyMatrixOperator`, I am planning for quite some time to rename `_matrix` to `matrix` to make data access more legitimate.

4. I could imagine adding a `tonumpy` method to `BlockOperator`. However, what about `LincombOperator`, `Concatenation`, `AdjointOperator`, `IdentityOperator`, etc..?

5. What about sparse matrices? In particular, when should `BlockOperator.tonumpy` assemble to a sparse matrix?  If I remember correctly, @ftalbrecht used such a method in the old `BlockOperator` to assemble a reduced sparse matrix in his LRBMS code.

6. In view of all these questions, my feeling is that we might want to proceed in spirit of #208 by adding a free `to_numpy` method.

To make it a little bit more clear what I mean by the 'rule-based' approach in #208: My current impression is that it might be a wiser design approach to keep in `OperatorInterface` only essential methods like `apply`, `apply_inverse`, `assemble_lincomb` which could not be (appropriately) implemented using the existing interface methods. All other methods like `projected` should be implemented using a rule table containing conditions and corresponding methods. Methods for matching conditions are called in order until the first methods succeeds. This approach should give much more flexibility to the user (by modifying the table) than using inheritance. For instance, one could easily match the name of a specific operator to tweak the behavior of `projected` for this operator, instead of creating a special type for the operator which then has to be instantiated at the right places.

In principle, such a rule-based approach is already implemented in `algorithms.image`, only that the table is hard-coded.

However, this approach also raises many questions. E.g., in which source file should the standard projection algorithm for `LincombOperator` be located? If its not in `projected.py` but in `operators.constructions`, then how to control the order of the entries in the rules table? If we put it in `projected.py` we separate algorithms from data. How will the traceback look like in case of errors?

Right now, I really do not know how we will proceed, but I want to make the relevant changes during the pyMOR 0.5 release cycle. This might take quite a few months, however.

If you need a solution now, I would propose to proceed similar to `algorithms.image`.

**Comment by pmli** [comment]
Ok, I will work on a recursive function in `algorithms` for extracting a matrix from a construction of `NumpyMatrixOperator`s.

I just want to point out that I opened this issue because of methods that can't even work with sparse matrices, only dense. So, at least here, an answer to 5. is clear. In general, the function could have an option to choose between sparse or dense.

**Comment by sdrave** [comment]
Fine!

**Comment by ftalbrecht** [comment]
I also lean towards (5) in the long run...

**Comment by sdrave** [comment]
@ftalbrecht, what do you mean by (5)?

**Comment by ftalbrecht** [comment]
By (5) I mean 6. :/

**Comment by sdrave** [comment]
This is related to #253 and #252.

**Comment by sdrave** [comment]
@pmli, can we close this or is there more work to do?

**Comment by pmli** [comment]
We can close. (I plan to add more tests for `to_matrix` and maybe some improvements later.)
