### ISSUE TITLE
Split `VectorArrayInterface.data` into several methods with clear semantics.

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#252]
Right now, `data` can be a (mutable) view of the `VectorArray` data or simply a copy. It might be better to have three methods which always return 
1. a copy
2. a readonly view or copy
3. a modifiable view

There should be a distinction between 1 and 2 for efficiency  reasons. Another option would be to make `data` a method an add appropriate parameters.

It is also unclear how `ListVectorArray` should behave. In many cases it would be desirable to have a list of numpy array views into the individual vectors. Should `data` be allowed to return a list of arrays in general? Should there be additional properties/methods?

**Comment by ftalbrecht** [comment]
Case 1 and 2 shall be handled by a method `arra()`, `numpy()`, `A()` or the like with a `copy` argument. Case 3 should not be handled in a generic way at all, since it is only of interest to implementors...

**Comment by pmli** [comment]
This sounds good to me.
I guess, in interactive sessions, `to_numpy()` is not so bad if auto-completion works, but `_d` would still be nice.

I would just like to see `to_numpy` and `from_numpy` with better documentation, specifically about the shape of the numpy array. I remember I was surprised in the beginning that the vectors are stored in rows instead of columns.

**Comment by ftalbrecht** [comment]
Sounds sound to me!
