### ISSUE TITLE
use python-versioneer for version string generation

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#294]
Given the many issues we have had with version strings, [this](https://github.com/warner/python-versioneer) might be something to look into, @renemilk?

**Comment by renemilk** [comment]
I skimmed the readme and didn't immediately see what we would be gaining by replacing our current setup.

**Comment by ebw44** [comment]
Hi have some issue when trying to `import pymor`. I think it's caused by the use of `import pymor.version as _version` in __init__.py which in return use __init__.py before version.py and cause an 'AttributeError'.
I did a simple change in the __init__.py to solve the problem, but it has the revstring hardcoded.
`        try:
            import pymor.version as _version
        except AttributeError:
            revstring = '0.4.1'
        else:
            revstring = getattr(_version, 'revstring', NO_VERSIONSTRING)`
instead of line 73 `import pymor.version as _version`

Here are the details about my system
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)] on win32
