### ISSUE TITLE
BlockVectorSpace(VectorSpace) == VectorSpace?

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#485]
If a `BlockVectorSpace` has only one subspace, should it be equivalent to this subspace? E.g., should the following code be made to work?
```python
import numpy as np
from pymor.operators.block import BlockOperator
from pymor.operators.numpy import NumpyMatrixOperator

A = NumpyMatrixOperator(np.ones((2, 2)))
v = A.source.from_numpy(np.array([1, 2]))
print(A.apply(v))

B = BlockOperator([[A], [A]])
print(B.apply(v))
```

This would make things more consistent for systems. Currently, addition/subtraction of `LTISystems` changes the input and output space to a `BlockVectorSpace`. Similarly when converting a `SecondOrderSystem` into an `LTISystem` via `to_lti`.

**Comment by sdrave** [comment]
I think identifying a `BlockVectorSpace` with one subspace with this subspace is messy, since the corresponding `VectorArrays` have different type and need to be treated differently in implementations.

In a private branch I have ad-hoc implementations of a `BlowRowOperator` and a `BlockColumnOperator` lying around which only have a `BlockVectorSpace` as `source` resp. `range`. Using those would probably solve all issues. However, as these are not (and cannot) be subclasses of `BlockOperator` special cases have to be introduced everywhere where `BlockOperators` are used.

An alternative would be to define a `BlockProjectionOperator` which when applied extracts one component of the `BlockVectorSpace`. Then one could achieve similar things by forming the `Concatenation` of a `BlockOperator` with a `BlockProjectionOperator` (or its transpose). This might be a little complicate from the user perspective, however.

If you agree that this is the right approach, I can prepare a PR for `BlockRowOperators` and `BlockColumnOperators`.

**Comment by pmli** [comment]
I haven't even thought of `BlockRowOperators` or `BlockColumnOperators`, they sound like a nice idea.
