### ISSUE TITLE
Rename discretizations to models

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#550]
At the dev meeting we have decided that we should rather speak of models than of discretizations: We are doing model reduction not discretization reduction, and not ever model comes from a discretization. Thus:

- `pymor.discretizations` -> `pymor.models`
- `StationaryDiscretization` -> `StationaryModel` and so on
- `d` -> `fom`
- `rd` -> `rom`

**Comment by sdrave** [comment]
As I understand this, we will also rename `LTISystem` to `LTIModel`? Right, @pmli?

**Comment by pmli** [comment]
It seems "model" is used quite a bit: https://www.mathworks.com/help/control/getstart/linear-lti-models.html

Looking at this, it might also make sense to use `StateSpaceModel` instead of `LTIModel`. On the other hand, `FirstOrderModel` would fit better with `SecondOrderModel`, `LinearDelayModel` and `BilinearModel`. Or maybe renaming `SecondOrderModel` to `SecondOrderStateSpaceModel` would be better... Maybe @gramian or @drittelhacker can comment.

**Comment by drittelhacker** [comment]
I would avoid `StateSpaceModel`, since that might require us to restart the discussion when we want to support differential algebraic systems. Think of an Oseen type system (DAE of differential index 2) with nv velocity and np pressure dofs. While the system would be represented by `nv+np` dofs, the actual state of the system, i.e. the solution of the implicit ODE, evolves on a `nv-np` dimensional manifold. Therefore some people would not call the FEM representation state and thus the DAE would not deserve the name `StateSpaceModel`, while it is still a linear time-invariant realization of the system/model, so `LTIModel` would be fine.

From a purely practical perspective, I would prefer the shorter names.When we require people to use a 4k screen to put a constructor on one line we clearly overdo in the descriptive naming scheme ;) To not go there I would avoid `SecondOrderStateSpaceModel`. Also, many people still use editors without auto-completion...

**Comment by pmli** [comment]
After an offline discussion with @drittelhacker, we concluded it would be good to involve more local people doing systems-theoretical MOR to find a nicer naming scheme for input-output models.

@sdrave For now, I think it's fine to rename discretizations and systems to models, and discuss in a different issue how to organize input-output and instationary models.

**Comment by gramian** [comment]
I would put forward `System` as this is what system theory is about.

**Comment by sdrave** [comment]
@gramian, in pyMOR we have the standing policy that classes that derive from `FooInterface` are of the name `BarFoo`. This convention is currently not followed by the system theory discretizations. Personally, I am very much in favor of this policy, as it makes it very clear to the newcomer of what type a given object is. Also, `System` does not make too much sense for the RB world, and I believe our main work in this area for the next release should be to unify things where possible.

I agree with @pmli that all further naming discussions should be carried out in a separate issue.
