### ISSUE TITLE
Testing of jupyter notebooks

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#571]
We need to integrate jupyter notebooks in our testing infrastructure. Some simple parameterization of notebooks should be supported.

**Comment by renefritze** [comment]
Maybe. I'm looking into it as one option.

**Comment by renefritze** [comment]
Papermill currently only supports collecting the variables for parameterizing in one single cell. I'm looking into extending that. 

What I'm also looking into will be marrying papermill with [panel](https://github.com/pyviz/panel)/[param](https://github.com/pyviz/param) from pyviz. Ideally we'd have very interactive and nice looking GUI controls automatically generated from a set of params from which papermill generates notebooks with realizations of param combinations of for testing.

**Comment by renefritze** [comment]
Started with #731

**Comment by pmli** [comment]
pyMOR dev meeting: parametrization for later release.

**Comment by renefritze** [comment]
I would say with the Sphinx RST to Notebook setup we're going with now we do not have a need for parameterized notebook testing any more. And since the code actually gets executed in producing notebooks with output, it's already tested. Plus notebooks in the /notebook dir have been runtested for a while already.
