### ISSUE TITLE
Find proper way to put notebooks under version control

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#572]
Git log should not be clobbered by minor changes to notebook metadata. Maybe convert notebooks to a more git-friendly format or run some cleanup script on them. We probably need some git hooks for that.

**Comment by pmli** [comment]
[This article](https://nextjournal.com/schmudde/how-to-version-control-jupyter) is the most comprehensive from those I found.
[jupytext](https://github.com/mwouts/jupytext) seems to be the best. Apparently, it somehow allows working with a Jupyter notebook as a plain text document. [This article](https://towardsdatascience.com/version-control-with-jupyter-notebooks-f096f4d7035a) shows how to use jupytext with R-markdown.

**Comment by sdrave** [comment]
Looks like `jupytext` could really help with a both git and user-friendly notebook workflow.

**Comment by renefritze** [comment]
My suggestion would be:
 - notebooks are add to git
 - *ipynb are automatically paired with *py, in [percent format](https://github.com/mwouts/jupytext#the-percent-format) since that works in quite a few editors, via jupytext
 - Unless explicitly marked output is stripped from notebooks via git-filter with [nbstripout](https://github.com/kynan/nbstripout)
 - The github app gets a check to enforce this output policy

I can bake the the jupytext setup into the notebook docker setup introduced in #602, but every developer not using that would need to merge a config file into his setup. Possibly whenever an update to it happens. I see no way around that since there's no such thing as directory-local configs for the notebook server.

Not sure what to do about cleaning metadata from notebooks before commit, but since we'd get "clean" diffs through the generated .py maybe that's not so much an issue then?

**Comment by renefritze** [comment]
@sdrave remarked offline that he does not want to include both a `.ipynb` and a `.py` in version control. 

That would mean we only add the .py scripts and let jupytext transparently open those as notebooks in jupyter. That however means we cannot embed any kind of cell output in version control. 
I don't think we want this restriction for all of our notebooks. This is IMO also an argument against automagically (re-) creating, possibly in a separate repo, `.ipynb`s from scripts in a CI step.

If we commit both paired files jupytext will at least not touch output of non-changed input-cells during `.py -> .ipynb` convert.

**Comment by sdrave** [comment]
> That however means we cannot embed any kind of cell output in version control.
I don't think we want this restriction for all of our notebooks.

I was assuming that it is one of the features to have no cell output under version control. What kind out output would you want to check in?

**Comment by renefritze** [comment]
Well, if you consider a tutorial-like series of notebooks I would think that presenting them pre-filled would be more appealing visually to the would-be user. 
Notebooks in documentation, although this might be hooked into with [nbsphinx](https://nbsphinx.readthedocs.io/en/0.4.2/), could also benefit from it.
Tracking output cells would also enable us to self-test those notebooks with [nbval](https://github.com/computationalmodelling/nbval)

**Comment by sdrave** [comment]
I believe we discussed to automatically commit evaluated notebooks in a separate repo?

**Comment by renefritze** [comment]
> I believe we discussed to automatically commit evaluated notebooks in a separate repo?

Insofar that it might be an option, yes. 
Looking further into though I don't think that's a good workflow. It makes automatic pairing with jupytext impractical. It makes CI more complicated since you'd now have to handle merges/conflicts/branches in the target repo too. 
I would rather put paired scripts/notebooks into a pymor/tutorial repo with no automagic sync in between.

**Comment by renefritze** [comment]
With the sphinx setup incoming, I guess this issue can be closed?

**Comment by sdrave** [comment]
Yes.
