### ISSUE TITLE
Implement output error bounds

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#575]
We should implement standard RB output error bounds based on the DWR approach.

**Comment by sdrave** [comment]
This will be handled by @TiKeil.

**Comment by TiKeil** [comment]
I thought a bit on that. 

1. I think this is rather easy to provide the DWR error estimator, if these two assumptions are required:

a) The output functional is linear
b) The stiffness matrix is symmetric

Is this PR also about the cases where a) and b) are not fulfilled?  
In case b) is not fulfilled we could skip the DWR approach but just go for the standard approach (first order estimator). So, should we provide the standard approach as well? 

2. Do we force each model to preassemble the output estimator in case the user provides an output functional?

**Comment by sdrave** [comment]
You can definitely assume that the output functional is linear. Regarding the stiffness matrix, handling the non-symmetric case is probably most interesting. However, finding a pyMOResque way to deal with non-symmetric problems in the DWR approach probably needs some discussion (regarding boundary treatment). So it might be a good option to only treat the symmetric case for the coming release. However, it would probably also be a good idea to have something for the general case in mind when writing the code.

I do not think that we should include the 'standard approach' of multiplying the residual norm by the norm of the functional as a new feature.

> Do we force each model to preassemble the output estimator in case the user provides an output functional or rather leave it optional?

I think we should default to assembling the output estimator when there is an output functional but provide an option to disable it.

**Comment by sdrave** [comment]
Hah, now that you have commented on the issue I can assign you, @TiKeil  ...

**Comment by TiKeil** [comment]
Ok thanks for your feedback.

**Comment by TiKeil** [comment]
While starting to work on this issue, I discovered another important question. So far (AFAIK), there is only THE estimator in pymor. Since this PR starts to incorporate an estimator for another quantity of a model it is important to think about how we treat this. 

For now, we use `build_rom(projected_operators, estimator)` while `_reduce()` is called by the reductor. Now, for an `output estimator` we should think about how we generalize to call the `build_rom()` function. To me there are mainly 2 possibilities for this. Please let me know if you have another suggestion which is better. 

1. Find a way to generalize the argument `estimator`, for example with `estimators` which could be a dict of multiple estimators. 
2. Add another argument `build_rom(projected_operators, estimator, output_estimator)`

No matter what we take, both require an extended review of all reductors I suppose. I would actually prefer 1. because of the following: Thinking about what happens if more estimators enter the reductors (for example for dual problems or sensitivities or derivatives of the output functional) the arguments would increase and increase which is not good in my opinion. Thus it would be nice to hide all estimators in only one generalization `estimators`.

Also, both options require to adjust the `estimate` in `Model`. For example one could have a separated function `estimate_output`. 

Note also: Of course, an output_estimator probably only makes sense for RB reductors from `coercive.py`. The others could potentially skip it, but this is also not obvious how we would do it... 

Do you have any thoughts?

**Comment by sdrave** [comment]
What about an `estimator` with an `estimate(..., return_output_estimate=False)` method and an `estimate_output()` method, and add another `estimate_output` method to the `Model`?

While we are at it: I think `estimate` is a really bad name. Maybe we should start with a separate PR that replaces `estimate` by something more reasonable: `estimate_error` (and `estimate_output_error`) for instance? I also would like `error_bound` but I do not think that we want to require each estimator to be an upper bound.

**Comment by TiKeil** [comment]
> What about an `estimator` with an `estimate(..., return_output_estimate=False)` method and an `estimate_output()` method, and add another `estimate_output` method to the `Model`?

sounds reasonable. That would mean to generalize `CoerciveRBEstimator` to the above suggested one and the main change would be in the instance of `CoerciveRBReductor` The `Model` (or the `Estimator`) then of course also need something like `solve_dual`, although this would only be needed to compute the bound. While thinking about `solve_dual` one could also think about generally providing a `DualModel` which is somehow available in `Model` and can also be used independently of the output bound. That however is a little bit more tricky. 

> While we are at it: I think `estimate` is a really bad name. Maybe we should start with a separate PR that replaces `estimate` by something more reasonable: `estimate_error` (and `estimate_output_error`) for instance? I also would like `error_bound` but I do not think that we want to require each estimator to be an upper bound.

I generally agree that there are better names than `estimate`. I dislike `error_bound` but `estimate_error` is something that we could consider.

**Comment by sdrave** [comment]
> While thinking about solve_dual one could also think about generally providing a DualModel which is somehow available in Model and can also be used independently of the output bound. That however is a little bit more tricky.

I think a dual model is needed to be able to get a dual ROM for the error estimate?

> I generally agree that there are better names than estimate. I dislike error_bound but estimate_error is something that we could consider.

Agreed. I will open a separate issue.

**Comment by TiKeil** [comment]
Yes it surely is needed but ofc it can also be hidden in the estimator without noticing that it actually is a dual model. That’s what I wanted to say with “it is not obvious where to provide what”

**Comment by sdrave** [comment]
Will not happen before release. Moving to next release.

**Comment by TiKeil** [comment]
One thing that I just tripped over... 

To estimate the output error with the DWR approach is only of course feasible for the compliant case or if the corrected output functional is used. Thus, it can not be used as a default error estimation for the output. 

We could provide a `dwr_corrected_output_functional` instead and add the estimation which comes out of this.
Otherwise I guess we would need to estimate the output with the standard approach.
