### ISSUE TITLE
Remove vector space ids?

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#609]
(Continuing from #581)

After merging #589 and #592, I'm not sure how necessary is to have vector space ids.

Internally, removing ids would simplify `models.iosys`, `algorithms.projection` and operators.

From the user perspective, it would be nice to simplify creating `rom0` for TSIA in `notebooks/heat.ipynb`, i.e. to have a good way to create a model with different operators, but the same input and output space. (I encounter this issue in general when working with non-projection-based methods.)

There should also probably be a better way to add the delay term in `notebooks/delay.ipynb`.

**Comment by sdrave** [comment]
So just a few remarks to make an informed decision:

- Reductors were the main reason for introducing `VectorSpace` ids. We have seen that this didn't work very well, and the new reductors no longer depend on the id mechanism.

- Ids had / have the tendency to get in the way in the sense that code fails just because you forgot to add an id somewhere.

- Still, for some use cases it might be useful to have them. In particular for debugging when you have a lot of spaces. (E.g. for localized RB methods, you can have a different id for spaces on each subdomain. Or for systems where you want to track with which solution variable a `VectorArray` is associated with.

- Ids are still used for [mpi_wrap_model](https://github.com/pymor/pymor/blob/master/src/pymor/models/mpi.py#L69) which automatically wraps mpi distributed operators. For this, one needs to know which `VectorSpaces` are actually mpi distributed. For instance, for an `LTIModel`, you typically would not have mpi distributed input or output spaces. In the current implementation, you can choose an id or a `VectorSpace` type to select the spaces which need wrapping. The type will usually be sufficient, as the mpi distributed arrays will typically not be `NumpyVectorArrays` whereas inputs and outputs will be. Still, there might be use cases, where the type is not sufficient, and it would be nice to provide the same automatism for these cases as well. (Nice but not necessary, as it wouldn't be a very complex task to implement a custom `mpi_wrap_model`.) Of course, in view of the recent reductor changes, one might also consider having variants of each `mpi_wrap_model` for each model type. However, this feels like unnecessary repetition to me.

- Keeping track of ids in `project` is really a pain.

- It is also a pain to have `source_id` and `range_id` params everywhere where an `Operator` instantiates a `VectorSpace` itself. This is currently the case for: `NumpyMatrixOperator`, `BlockOperator` and variants, as well as `VectorArrayOperator`.

- Enforcing id in `models.iosys` really does not seem useful anymore.

I totally agree that ids should be removed from `project` as well as from most parts of `models.iosys` (maybe keep them for the `from_...` factories?)

I am not sure if we want to completely remove ids. Any other opinions, @pymor/pymor-devs?

**Comment by renefritze** [comment]
I very much like the idea of keeping them in a manner that does not get in the way of the user adding a new model/projection/whatever.

**Comment by sdrave** [comment]
So how about an incremental (or decremental) approach? Let's remove ids in `project` and `models.iosys` and see where this leads us?

**Comment by ftalbrecht** [comment]
No objections

**Comment by sdrave** [comment]
@pmli, what do you think about the current state? Shall we close this for now and re-discuss space ids after the next release?

**Comment by pmli** [comment]
@sdrave I like the current state. There is just #617 which fixes a bug in heat.ipynb. Otherwise, I think this can be closed.
