### ISSUE TITLE
Add dtype attribute to VectorSpace

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#670]
Motivation:
- add more support for complex numbers (see https://github.com/pymor/pymor/pull/669#issuecomment-481337987, https://github.com/pymor/pymor/pull/323#issuecomment-262274160)
- add support for (potential) mixed precision algorithms (see https://github.com/pymor/pymor/pull/362#discussion_r111117960)

`VectorSpace` methods (`zeros`, `ones`, ...) would then have to take `dtype` into account.

**Comment by renefritze** [comment]
To add to motivation: I've run into a related issue in #671. A lincomb of a vectorarray with complex values and complex coefficients will fail due to unsafe casting after lincomb internally creates a zero_vector with float dtype to which no complex arrays can be added. 

This is somewhat of a blocking issue for me, so I'll tackle this in separate PR asap.

**Comment by sdrave** [comment]
I think we decided at the last dev meeting to give up on this for now, so I would close the issue. Agreed, @pmli, @renefritze?

**Comment by pmli** [comment]
Yes, agreed.
