### ISSUE TITLE
ordering of parameters dict depends on python version

### ISSUE THREAD

**Issue by ftalbrecht** [pymor/pymor#726]
@TiKeil knows more about this

**Comment by sdrave** [comment]
I believe the issue was that `ParameterType` is not guaranteed to be ordered, whereas we always implicitly assume an alphabetical ordering of `Parameter` components.

**Comment by TiKeil** [comment]
I am not sure... I believe `ParameterType` is always ordered correctly but the `__string__` method calls `dict( )` of an ordered dict and the output of this is not necessarily ordered the same way.

**Comment by sdrave** [comment]
@TiKeil, you are right that `ParameterType.__str__` calls `str(dict(self))` and for Python 3.6 no ordering is guaranteed by the spec, although the new `dict` implementation of CPython is insertion ordered. Do you want to fix the code? BTW, since CPython 3.7, insertion ordering of dicts is part of the specification: https://mail.python.org/pipermail/python-dev/2017-December/151283.html
