### ISSUE TITLE
Generic algorithm for approximating eigenvalues

### ISSUE THREAD

**Issue by lbalicki** [pymor/pymor#774]
A generic algorithm that approximates a few of the largest/smallest eigenvalues of an `Operator` would be a useful addition for pyMOR.

One place where this would be useful is the computation of a few more types of shift parameters for the low-rank ADI methods for solving matrix equations. Also in the `adaptive_rrf` function in `algorithms/randrangefinder.py` the smallest eigenvalue of an operator needs to be computed.

**Comment by drittelhacker** [comment]
if `Operator` is symmetric this relates to #772

**Comment by sdrave** [comment]
For `adaptive_rrf` we need the smallest eigenvalue of the inner product. However, here a relative error of 1 (or even larger) would be totally acceptable. Since this is a randomized method, it would be attractive to use a randomized SVD alg to compute the eigenvalue.

It should be noted however, that the smallest eigenvalue is required for a very crude error estimate you get when you do the randomized sampling w.r.t. the Euclidean inner product instead of the actual inner product of the Hilbert space. Someone should come up with something smarter and write a paper about it. (At least we in Münster are not aware of anyone having already solved that issue.)

**Comment by lbalicki** [comment]
@sdrave yes, I would be interested in looking into this. At first glance, it seems to me that randomized SVD algorithms for Operators in pyMOR will require a SVD algorithm for VectorArrays. So will I have to take a look at that first or will #718 (SVD for VectorArrays using Gram-Schmidt) be added to pyMOR?

**Comment by sdrave** [comment]
@lbalicki, #718 definitely should be added to pyMOR. It only needs a little bit more work, I guess.

**Comment by pmli** [comment]
Can this be closed?

**Comment by sdrave** [comment]
Yes.
