### ISSUE TITLE
Specify FEniCS and NGSolve versions in requirements-optional.txt?

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#857]

**Comment by renefritze** [comment]
My general opinion is we should add only packages in requirements/dependencies that are pip installable from  pypi without the user having to manually adjust/call pip.

While you can `pip install fenics`, this does not get you dolfin, which means it's mostly useless if the user does not also install dolfin (and other fenics deps) manually.  If we could `pip install pymor fenics && pymor-demo  fenics_nonlinear 2 10 2` without issue that would be great, but that's not possible (yet?). 
Ngsolve has no package on pypi at all.

What I think we can do instead of prescribing versions via requirements is emit a warning (disableable) if the user has a version not matching the reference version we run our CI against. I'm somewhat sure @sdrave and I already had this plan a while back, but I couldn't find a trace of that.

**Comment by pmli** [comment]
Then how about specifying the versions in `README.md`?

**Comment by renefritze** [comment]
> Then how about specifying the versions in `README.md`?

We can do that, sure. We should add an item to the release checklist to match the README ones to actual CI ones then I think.

**Comment by sdrave** [comment]
So currently `config.HAVE_FENICS` will issue a warning when the FEniCS version differs from what we are currently (presumably) testing with. We could add a remark to `README.md`, but this will add maintenance burden and probably will keep away users with a different FEniCS version, even though it will probably work. So I would vote for  keeping the current situtation.

Regarding NGSolve, we should probably have another discussion with them about release cycles before fixing any NGSolve version in pyMOR.

**Comment by pmli** [comment]
I would be for adding something like "pyMOR bindings for FEniCS and NGSolve are tested using version x and y" to `README.md`. What are the actual versions used in testing?

If you agree, I would then open a PR.

**Comment by renefritze** [comment]
[2019.1.0](https://github.com/pymor/docker-all/blob/master/fenics/docker/Dockerfile#L7) and [v6.2.2001](https://github.com/pymor/docker-all/blob/master/ngsolve/docker/Dockerfile#L19)
I'll take this issue as an excuse to finally add an info script to the docker stack that prints version info for everything. So in the future you'd go `docker pull pymor/testing_py.38:latest && docker run -t pymor/testing_py.38:latest pymor-info` and everything one would want to know.

**Comment by renefritze** [comment]
Once the [CI build](https://zivgitlab.uni-muenster.de/pymor/docker-all/pipelines/59822) is done you can indeed run 
```sh
docker pull pymor/testing_py3.8:latest && \
docker run -t pymor/testing_py3.8:latest pymor-info
```
To get 
| Project  | Installed Version |
|----------|-------------------|
| python   | 3.8.2.final       |
| deal.II  | 9.0.1             |
| FEniCS   | 2019.1.0          |
| NGSolve  | v6.2.2001         |
| PETSc    | 3.12.3            |
| pybind11 | 2.4.3             |
| Trilinos | 12.10.1           |


via [this commit](https://github.com/pymor/docker-all/commit/24942eacc7f3bba62224efcaece2c0024daec9dc)
