### ISSUE TITLE
Default tolerances for newton algorithm

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#896]
The current defaults for `pymor.algorithms.newton.newton` force the algorithm to never converge. Previously, we had `stagnation_threshold` set to `0.9` which seemed toopermissive for a default convergence criterion. @pymor/pymor-devs, @TiKeil, @lbalicki, do you have any opinions on this?

Also, note that all current stopping criteria are based on the Euclidean norm of the residual, whereas the norm of the update is also frequently used. Should we implement both (this is what FEniCS does)? I have also seen the dual norm of the residual being used in an NGSolve tutorial. I am not sure if it makes sense to implement everything one might possibly think of ..

**Comment by pmli** [comment]
[SciPy](https://github.com/scipy/scipy/blob/6bb954d3ce5c743b008bc9036dc29e6f34640b80/scipy/optimize/zeros.py#L187-L189) uses only the norm of the update...

**Comment by sdrave** [comment]
Also note that `rtol` and `atol` is not really useful when using the algorithm for residual minimization. @HenKlei, you have worked on the method before. Do you have any opinions on this?

**Comment by HenKlei** [comment]
Prescribing `rtol` or `atol` does not seem to make sense, that's right. I mean, since we do not know beforehand which accuracy is required by the user, we should not abort the Newton iteration if the residual is still decreasing (at least not by default and at fixed tolerances, I think). Therefore, I would prefer the approach of trying to perceive stagnation in the residual. However, finding proper default values for `stagnation_window` and `stagnation_threshold` seems to be quite difficult as well.
